version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - minio
      - redis
    restart: always

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    restart: always

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

volumes:
  mongo_data:
  minio_data:
  redis_data: 